apiVersion: apps/v1
kind: Deployment
metadata:
  name: TestApp1
spec:
  selector:
    matchLabels:
      app: TestApp1
  template:
    metadata:
      labels:
        app: TestApp1
    spec:
      containers:
      - name: TestApp1
        image: none/none
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: TestApp1
spec:
  selector:
    app: TestApp1
  type: NodePort
  ports:
  - port: 5000
    targetPort: 9003
  # notePort: 30080
